In [1]:
import numpy as np
from CombTask import CombinationGame as CG
from ProgressionTree import ProgressionTree as PT

In [2]:
def test_combination_game():
    # create an environment

    # reset and render the environment for 1 to 10 objects
    for i in range(1, 3):
        env = CG(1)
        # reset the environment
        env.reset(i)
        # render the environment
        print(f"grid for {i} object\n", env.render())

In [3]:
env = CG(1)
grid_size = 7

def print_free_indices(grid_size, indices_list):
    grid = np.zeros((grid_size, grid_size))
    for i in indices_list:
        grid[i[0], i[1]] = 1
    print(grid)
indices = np.array(np.unravel_index(range(grid_size*grid_size), (grid_size, grid_size))).T
print_free_indices(grid_size, indices)

new_indices = env._remove_position_and_neighbors([1, 1], indices)
print_free_indices(grid_size, new_indices)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [6]:
env = CG(2)
env.reset(15)
print(env.render())

KeyboardInterrupt: 