In [1]:
import numpy as np
from CombTask import CombinationGame as CG
from ProgressionTree import ProgressionTree as PT

In [2]:
def test_combination_game():
    # create an environment

    # reset and render the environment for 1 to 10 objects
    for i in range(1, 3):
        env = CG(1)
        # reset the environment
        env.reset(i)
        # render the environment
        print(f"grid for {i} object\n", env.render())

In [3]:
env = CG(1)
grid_size = 7

def print_free_indices(grid_size, indices_list):
    grid = np.zeros((grid_size, grid_size))
    for i in indices_list:
        grid[i[0], i[1]] = 1
    print(grid)
indices = np.array(np.unravel_index(range(grid_size*grid_size), (grid_size, grid_size))).T
print_free_indices(grid_size, indices)

new_indices = env._remove_position_and_neighbors([1, 1], indices)
print_free_indices(grid_size, new_indices)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [4]:
env = CG(2)

In [5]:
env._random_init(1)
print(env.render())

depth:  0 nodes:  [0]
depth nodes strings:  ['  ']
value:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] id:  0
	Node:  g  Possible Combinations:  ['ii', 'lm', 'mm', 'ml']  Is_Leaf?  False
YOOOOOOO 1  [0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0]
YOOOOOOO 2  [0 0 0 0 0 0 0 0 0 0 0 0] [0 1 0 1 0 0 0 0 0 0 0 0]
		Found Combination:  ['m-', 'l']
	Found Combination:  ml
1
1
depth:  1 nodes:  [[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]]
depth nodes strings:  ['m-0', 'l0']
value:  [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] id:  1
	Node:  m  Possible Combinations:  ['mm', 'ml', 'lm']  Is_Leaf?  False
YOOOOOOO 1  [0 1 0 1 0 0 0 0 0 0 0 0] [0 1 0 1 0 0 0 0 0 0 0 0]
YOOOOOOO 2  [0 1 0 1 0 0 0 0 0 0 0 0] [0 2 0 2 0 0 0 0 0 0 0 0]
		Found Combination:  ['m-', 'l']
	Found Combination:  ml
2
2
value:  [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.] id:  10
	Node:  l  Possible Combinations:  ['mm']  Is_Leaf?  False
YOOOOOOO 1  [0 2 0 2 0 0 0 0 0 0 0 0] [0 2 0 2 0 0 0 0 0 0 0 0]
YOOOO

KeyError: ' '

In [ ]:
object_string = "m-3"
entity_string_doc_reverse = {
            "m+": 0,
            "m-": 1,
            "a": 2,
            "l": 3,
            "i+": 4,
            "i-": 5,
            "X": 6,
        }
object_id = int(object_string[2:]) if len(object_string) > 2 else int(object_string[1])
object_type = entity_string_doc_reverse[object_string[0:2]] if len(object_string) > 2 else entity_string_doc_reverse[object_string[0]]
object_type, object_id

(1, 3)